export const SAVE_SEARCHED_HOTELS = "SAVE_SEARCHED_HOTELS";
export const SAVE_SEARCH_HOTEL_ERROR = "SAVE_SEARCH_HOTEL_ERROR";
export const SEARCH_HOTELS_LOADED = "SEARCH_HOTELS_LOADED";
export const SAVE_SEARCH_HOTEL_STATUS ="SAVE_SEARCH_HOTEL_STATUS";
export const SAVE_SEARCH_HOTEL_STATUS_ERROR = "SAVE_SEARCH_HOTEL_STATUS_ERROR";
export const SAVE_SEARCH_HOTEL_STATUS_LOADED ="SAVE_SEARCH_HOTEL_STATUS_LOADED";